name: Test Omnilogic

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Print XCODES
      run: ls -n /Applications/ | grep Xcode*
    - name: Build
      working-directory: ./OmniLogic
      run: swift build -v
    - name: Run tests
      working-directory: ./OmniLogic
      run: swift test -v
