name: Test Omnilogic

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1.17.0
      with:
        swift-version: "5.7.0"
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ./OmniLogic
      run: swift build -v
    - name: Run tests
      working-directory: ./OmniLogic
      run: swift test -v
