name: Test Omnilogic

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Switch to package dir
      run: cd OmniLogic/
    - name: Ls current dir
      run: ls
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
